# https://github.com/pixijs/pixi.js/blob/dev/.github/workflows/nodejs.yml
# https://github.com/actions/setup-node
name: Node.js CI

on:
  push:
    branches: ['**']
    tags: ['**']
  release:
    types: ['created']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
